"""TamanduCLI internal API (BLE, wire protocol, registry, I/O helpers)."""

from api.ble_nus import NordicUARTService, scan_devices
from api.command_handlers import (
    BLE_CAPTURE_HOOKS,
    BLE_TRY_FEED_HOOKS,
    CLI_COMMAND_HANDLERS,
    DEFAULT_LIST_BATCH_ACK_TIMEOUT_SECONDS,
    DEFAULT_LIST_BATCH_MESSAGES_BEFORE_ACK,
    INCOMING_MESSAGE_HANDLERS,
    CliHandlerContext,
    NusPort,
    WireCommand,
    cli_command,
    dispatch_ble_notification,
    dispatch_cli_command,
    incoming_command,
    incoming_handler,
    register_ble_capture,
    register_ble_try_feed,
    register_cli_command,
    register_incoming_command,
    send_homogeneous_list_body_requests_batched,
)
from api.incoming import IncomingRouter
from api.list_wire import (
    ListWireCollectionSession,
    ble_message_has_list_wire_response,
    feed_list_wire_collection_from_ble_text,
    list_response_header_row_total,
)
from api.protocol_utils import (
    DEFAULT_WIRE_MESSAGE_MAX_BYTES,
    WireListHeader,
    batch_wire_messages,
    format_batched_wire_message,
    format_message,
    format_wire_command,
    normalize_cli_input,
    pack_list_body_requests_into_batched_wire_messages,
    parse_message,
    parse_wire_command_segment,
)
from api.realtime import (
    REALTIME_VARIABLES,
    RealtimeVariableSpec,
    register_realtime_variable,
)

__all__ = [
    "BLE_CAPTURE_HOOKS",
    "BLE_TRY_FEED_HOOKS",
    "CLI_COMMAND_HANDLERS",
    "INCOMING_MESSAGE_HANDLERS",
    "CliHandlerContext",
    "DEFAULT_LIST_BATCH_ACK_TIMEOUT_SECONDS",
    "DEFAULT_LIST_BATCH_MESSAGES_BEFORE_ACK",
    "IncomingRouter",
    "NordicUARTService",
    "NusPort",
    "WireCommand",
    "WireListHeader",
    "DEFAULT_WIRE_MESSAGE_MAX_BYTES",
    "batch_wire_messages",
    "format_batched_wire_message",
    "pack_list_body_requests_into_batched_wire_messages",
    "cli_command",
    "dispatch_ble_notification",
    "register_ble_capture",
    "register_ble_try_feed",
    "dispatch_cli_command",
    "format_message",
    "format_wire_command",
    "incoming_command",
    "incoming_handler",
    "normalize_cli_input",
    "parse_message",
    "parse_wire_command_segment",
    "REALTIME_VARIABLES",
    "RealtimeVariableSpec",
    "register_realtime_variable",
    "register_cli_command",
    "register_incoming_command",
    "scan_devices",
    "send_homogeneous_list_body_requests_batched",
    "ListWireCollectionSession",
    "ble_message_has_list_wire_response",
    "feed_list_wire_collection_from_ble_text",
    "list_response_header_row_total",
]
